### PR TITLE
automatically hide navigation icon on mobile

### PR DESCRIPTION
**Pull request by PSheon**
Hello Halyul
I found that navigation icon will block the next page icon on the mobile
so I just let the navigation icon hidding when user scroll to bottom

thanks

### CODE REVIEW

**Comment by EYHN** [comment]
How can this problem occur and can you provide screenshots or other information?

**Comment by Halyul** [comment]
You should use dev branch. I have updated the post pagination style, this problem should be disappear.

**Comment by Halyul** [comment]
But I think you give me a new idea on this problem, I will add it to dev branch XD

**Comment by PSheon** [comment]
Oh I got it！It works perfect !

**Pull request closed without merging**
